# Generated by Django 3.2.12 on 2022-03-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_date', models.DateTimeField(blank=True, null=True)),
                ('max_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
